[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run migrate && next start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
